---
- name: Configure routers
  hosts:
    - inetRouter
    - centralRouter
    - office1Router
  become: true
  gather_facts: false
  roles:
    - ip_forward
    - nftables

- name: Common provision
  hosts: all
  become: true
  gather_facts: false
  roles:
    - network_config
