---
ip4: '192.168.0.1'

nmcli_connections:
  - conn_name: System eth0
    ifname: eth0
    gw4_ignore_auto: true
  - conn_name: central-inet-bond
    ifname: bond0
    type: bond
    mode: '802.3ad'
    xmit_hash_policy: layer3+4
    mtu: 1500
    ip4: '192.168.255.2/30'
    gw4: '192.168.255.1'
    custom: [[bond, lacp_rate, 1]]
  - conn_name: central-inet
    slave_type: bond
    master: bond0
    ifname: eth1
    custom: [[ethernet, accept-all-mac-addresses, 1]]
  - conn_name: central-inet2
    type: bond-slave
    slave_type: bond
    master: bond0
    ifname: eth2
    custom: [[ethernet, accept-all-mac-addresses, 1]]
  - conn_name: central-office1
    ifname: eth3
    ip4: '192.168.255.9/30'
    routes4: ['192.168.2.0/24 192.168.255.10']
  - conn_name: central-directors
    ifname: eth4
    ip4: '192.168.0.1/28'
  - conn_name: central-hardware
    ifname: eth5
    ip4: '192.168.0.33/28'
  - conn_name: central-wifi
    ifname: eth6
    ip4: '192.168.0.65/26'
