---
ip4: '192.168.2.67'

nmcli_connections:
  - conn_name: System eth0
    ifname: eth0
    gw4_ignore_auto: true
  - conn_name: office1-test
    ifname: eth1
    ip4: '192.168.2.67/26'
    gw4: '192.168.2.1'
  - conn_name: vlan2
    ifname: eth1.2
    type: vlan
    vlandev: eth1
    vlanid: 2
    ip4: '10.10.10.1/24'
